### ISSUE TITLE
RedisQFork files filling up the disk

### ISSUE THREAD

**Issue by jimmymain** [microsoftarchive/redis#87]
Hi,

The new branch 2.8.4_msopen creates memory mapped files.
The files are not recycled however, so eventually the redis server will run out of disk space.

The files are significantly large enough for this to be a problem.

**Comment by dionoid** [comment]
On my system (Windows 8.1 Enterprise, Build 9600) when stopping the "redis-server" process, the RedisQFork file is removed and disk space is freed up again. What version of Windows are you using?

--Dion

**Comment by jimmymain** [comment]
Hi,

Also windows 7, and so does mine. The problem is that I reboot my machine
daily. When running as a service and the machine is rebooted the file is
not recycled.

Hope that helps
Cheers
Craig

**Comment by jepickett** [comment]
I have fixed this with  commit 959c9d3469b9e81cee97e59fd1c6156df8714c80. The service was reporting that it was done before the service thread had completed termination.

**Comment by jepickett** [comment]
Has the code change fixed your problem?

**Comment by jepickett** [comment]
Since I have not heard back on this issue, I am assuming that it is fixed. I am closing this issue for now.

**Comment by jimmymain** [comment]
Hi Jonathan,

I will get the latest code and build again and test for you.
My experience is that the file gets correctly deleted as long as don't
reboot the machine.

Perhaps the service code needs to check for reboots as well as the checks
currently being done.

If the problem persists I will try and put a pull request In for the fix.

**Comment by rainabba** [comment]
I JUST downloaded and installed 2.8.13 a week ago and today noticed my disk was dangerously full. Used WinDirStat and came to find this issue. I've only run it once and don't appear to be running as a service. I'm going to delete the file for now since from what I've read, it shouldn't heard anything, but it appears the issue still exists in some form.

**Comment by jepickett** [comment]
@rainabba 
Have you been able to reproduce the problem? Did your system encounter a BSOD, or was otherwise forcefully powered off?

**Comment by jepickett** [comment]
@rainabba 

I am going to close this issue for lack of a reproduction scenario. If this issue happens again, let me know about the conditions in which it manifests.

**Comment by jimmymain** [comment]
We are using the latest build in production, and we have not had any issues since [959c9d3](https://github.com/MSOpenTech/redis/commit/959c9d3469b9e81cee97e59fd1c6156df8714c80).
I am pretty sure it's resolved.
